baseurl: ""
relativeURLs: "True"
languageCode: "en-us"
title: 'HumLUG - Humboldt Linux Users Group'
theme: "hugo-minimal"
footnotereturnlinkcontents: "↩"
disableHugoGeneratorInject: true

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Announcements
      url: "announcements/"
      weight: 3
    - name: Events
      url: "events/"
      weight: 4
    - name: Event Notes
      url: "event_notes/"
      weight: 5
    - name: Example
      url: "example/"
      weight: 6
    - name: Knowledge
      url: "knowledge/"
      weight: 7
    - name: Join
      url: "join/"
      weight: 8

params:
  description: "Official website of the Humboldt Linux Users Group (HumLUG)."
  footer: "All logos and trademarks in this site are property of their respective owner. Anything else not covered by it's own copyright is &copy; 2025 -- {Year} humlug.org -- [Github repo](https://github.com/mrdatawolf/humlug.com) -- Contact the site [admin](mailto:humlug@humboldt.edu)"
